#####
name: CycleGan
noise_level: 1  #  noise level
port: 8097   #  port parameters 6019 8097
save_root: './output/Cyc/model/'
image_save: './output/Cyc/img2/e5/'

# lamda weight
Adv_lamda: 1
Cyc_lamda: 10
Corr_lamda: 20
Smooth_lamda: 10

epoch: 0        # starting epoch
n_epochs: 60       # How often do you want to display output images during training
batchSize: 1               # size of the batches
train_list: './data/train.txt'     # root directory of the dataset
val_list: './data/val.txt'
test_list: './data/test2d2.txt' #test2d2
lr: 0.0001                   # initial learning rate
decay_epoch: 20            # epoch to start linearly decaying the learning rate to 0
size: 512                # size of the data crop 512
input_nc: 1         
output_nc: 1                  
cuda: True                
n_cpu: 1

