#####
name: P2p
noise_level: 1
save_root: './output/P2P/model/'
image_save: './output/P2P/val2/e28/'
port: 8097   #  port parameters
# lamda weight
Adv_lamda: 1
P2P_lamda: 100

epoch: 0        # starting epoch
n_epochs: 60       # How often do you want to display output images during training
batchSize: 1               # size of the batches
train_list: './data/train.txt'     # root directory of the dataset
val_list: './data/val.txt'
test_list: './data/val2.txt'
lr: 0.0001                   # initial learning rate
decay_epoch: 20            # epoch to start linearly decaying the learning rate to 0
size: 512                # size of the data crop
input_nc: 1         
output_nc: 1                  
cuda: True                
n_cpu: 1

